### ISSUE TITLE
overhaul web-gui

### ISSUE THREAD

**Issue by maxbirnbacher** [AetherAerospace/hawk-groundcode#10]
Add interactive map (Mapbox GL JS) with functionality to add custom waypoints
Overhaul style-guide
Add basic controls for airplane (fts button, etc.)

**Comment by 0xk1f0** [comment]
to be closed with [`fda7152`](https://github.com/AetherAerospace/hawk-groundcode/commit/fda71525d734590cbc4142817d3acaff4efd7d96)?

**Comment by maxbirnbacher** [comment]
Done
