### ISSUE TITLE
add ability to call ESP32 functions via API

### ISSUE THREAD

**Issue by felixslama** [AetherAerospace/hawk-groundcode#12]

**Comment by maxbirnbacher** [comment]
GET (/getflightdata):
- Location
- Bearing
- Pitch
- Yaw
- Altitude
- Roll

POST (/postwaypoints):
- Waypoints (Location, Waypoint Type)

POST (/postmissionstatus):
- Mission status (ready/not ready)

POST (/postterminatemission):
- Terminate mission (true/false)

**Comment by 0xk1f0** [comment]
orphaned/no longer needed
